apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandeep-pv17
  namespace: ns11
  labels:
    type: fast-11
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /srv/nfs/kubedata/pyapp    # Path exported by your NFS server
    server: 172.31.11.26    # Replace with your NFS server’s IP
