apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deploy-11
  namespace: ns11
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: python-app-11
  template:
    metadata:
      labels:
        app: python-app-11
    spec:
      containers:
        - name: python-container
          image: gonurup/py-may26:${IMAGE_TAG}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis-service-11"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          #volumeMounts:
          #- mountPath: "/code"
          #  name: my-storage-11
      volumes:
      - name: my-storage-11
        persistentVolumeClaim:
          claimName: sandeep-pvc17              