apiVersion: v1
kind: Service
metadata:
  name: py-service-11
  namespace: ns11
spec:
  type: NodePort
  selector:
    app: python-app-11
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30111
