apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonApp.serviceName }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.pythonApp.service.type }}

  selector:
    app: {{ .Values.pythonApp.name }}

  ports:
    - port: {{ .Values.pythonApp.service.port }}
      targetPort: {{ .Values.pythonApp.service.targetPort }}
      nodePort: {{ .Values.pythonApp.service.nodePort }}