apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.deploymentName }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.redis.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ .Values.redis.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}

    spec:
      containers:
        - name: redis-container

          image: {{ .Values.redis.image }}

          ports:
            - containerPort: 6379

          resources:
{{ toYaml .Values.redis.resources | indent 12 }}